package simulation;
import java.text.DecimalFormat;

/*
 * The numbers generated by java Random is using Uniform Distribution. 
 * But recently, when I work on Timed-Petri net, it is better to use Exponential Distribution.
 * Thus, I write a class which is like a exponential calculator.
 * 
 * INPUT: lambda
 * OUTPUT: random number based on Exponential Distribution
 */

public class ExponentialDistribution {

	/*
	 * Call getExponential(double times) to get the random number
	 */
	public int getExponential(double times) {
		int y;
		double x,z;
		double lambda = 1 / times;
		z = Math.random();
		x = (-(1 / lambda) * Math.log(z));
		y = format(x);
		return y;
	}

	/*
	 * Call format(double x) to modify the double value x into which only has
	 * two digit after decimal point
	 */
	public int format(double x) {
		return Integer.parseInt(new DecimalFormat("#").format(x));
		//return Double.parseDouble(new DecimalFormat("##.##").format(x));
	}
}

