package GUIFinal2;

public enum Button{CLEAR_ALL, STEP_BY_STEP, STOP,
	ADD_PLACE, ADD_TOKEN, ADD_TRANSITION,ADD_ARC,
	TRANS_ADD_ARC,PLACE_ADD_ARC, RUN,
	
	TRANS_DELETE_ARC,PLACE_DELETE_ARC,
	DELETE_PLACE, DELETE_TOKEN,DELET_TRANSITION, DELETE_ARC, 
	SAVE_FILE, PANEL,
	NORMAL_MODE                       };